### ISSUE TITLE
tutorial updates

### ISSUE THREAD

**Issue by McHaillet** [SBC-Utrecht/pytom-match-pick#102]
Some updates for the tutorial:
- [x] reduce number of GPU's, see issue #99 
- [x] add note on volume tiling, see issue #101
- [x] add note on template box size, see issue #72
- [x] point to wiki page with pytom star file conventions

**Comment by McHaillet** [comment]
All done!
